@startgantt
title Реальный прогресс - 2026-Q2
Project starts 2026-04-01
saturday are closed
sunday are closed

2026/05/01 is closed
2026/05/09 is closed
2026/05/11 is closed
2026/06/12 is closed

printscale daily zoom 1.5
projectscale daily
today is colored in LightSalmon
!$now = %now()
[Мы сейчас здесь] as [TODAY_MARK] happens %date("YYYY-MM-dd", $now)

<style>
ganttDiagram {
  task {
    BackGroundColor lightblue
  }
  milestone {
    BackGroundColor orange
    FontColor black
  }
}
</style>
' Реальный прогресс

!include preamble/common.puml

-- Согласования --
!include includes/actual-progress/FEATURE-approvals.puml

-- Внедрения --
!include includes/actual-progress/FEATURE-deployments.puml

-- Пакеты --
!include includes/actual-progress/FEATURE-packages.puml

-- Скоркарты --
!include includes/actual-progress/FEATURE-scorecards.puml

@endgantt
