@startgantt
title План на квартал - 2026-Q2
Project starts 2026-03-30
saturday are closed
sunday are closed

2026/05/01 is closed
2026/05/09 is closed
2026/05/11 is closed
2026/06/12 is closed

printscale daily zoom 1.5
projectscale daily
today is colored in LightSalmon
!$now = %now()
[Мы сейчас здесь] as [TODAY_MARK] happens %date("YYYY-MM-dd", $now)

<style>
ganttDiagram {
  task {
    BackGroundColor lightblue
  }
  milestone {
    BackGroundColor orange
    FontColor black
  }
}
</style>
' План на квартал

!include preamble/common.puml

-- Согласования через SberDocs --
!include includes/quarter-plan/FEATURE-approvals.puml

-- Артефакты --
!include includes/quarter-plan/FEATURE-artifacts.puml

-- Внедрения --
!include includes/quarter-plan/FEATURE-deployments.puml

-- Пилоты --
!include includes/quarter-plan/FEATURE-pilots.puml

-- Ролевая модель и RBAC --
!include includes/quarter-plan/FEATURE-roles.puml

-- Скоркарты --
!include includes/quarter-plan/FEATURE-scorecards.puml

-- Симуляции --
!include includes/quarter-plan/FEATURE-simulations.puml

-- Табличные риск-параметры --
!include includes/quarter-plan/FEATURE-tabular-risk-parameters.puml

@endgantt
